#@name get-prompts
GET http://localhost:3333/prompts


###

#@name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

#@name create-trancription
POST http://localhost:3333/videos/d969e73a-6158-4e18-901e-898cefc926c1/transcription
Content-Type: application/json

{
	"prompt": "sol, mar, amargo"
}

###

#@name genarate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
	"videoId": "d969e73a-6158-4e18-901e-898cefc926c1",
	"temperature": 0.5,
	"prompt": "genarate an overall of the video: ''' {transcription}'''"
}